"""
ForexPro Professional Telegram Bot
Brand: ForexPro | @profxlover
USDT TRC20: TTWYTUp1VEbTkQJcwnmujwsfKJ6Ud3Y3au
Strategy: 2MA + Andean Oscillator (EURUSD, EURCAD, USDCAD - 4H)
"""

import logging
from telegram import (
    Update, InlineKeyboardButton, InlineKeyboardMarkup,
    ReplyKeyboardMarkup, KeyboardButton
)
from telegram.ext import (
    ApplicationBuilder, CommandHandler, MessageHandler,
    CallbackQueryHandler, ContextTypes, filters
)

# ─── CONFIG ───────────────────────────────────────────────────────────────────
BOT_TOKEN   = "8983303476:AAFNRMM6HiEUIKmywDjV1AANQ4M5HLC47yI"   # Replace after BotFather setup
OWNER_ID    = 8012381227               # Your Telegram numeric user ID
USDT_ADDR   = "TTWYTUp1VEbTkQJcwnmujwsfKJ6Ud3Y3au"
CHANNEL_URL = "https://t.me/profxlover"

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s", level=logging.INFO
)

# ─── TEXTS ────────────────────────────────────────────────────────────────────

WELCOME = """\
🏆 *Welcome to ForexPro* — Elite Forex Trading

━━━━━━━━━━━━━━━━━━━━━━━
Your professional gateway to consistent forex profits.

✅ Live trading signals (EURUSD · EURCAD · USDCAD)
✅ Advanced EA — 2MA + Andean Oscillator strategy
✅ Managed account services
✅ 24/7 dedicated support

━━━━━━━━━━━━━━━━━━━━━━━
Use the menu below to explore our services.
"""

SERVICES = """\
💼 *ForexPro — Services & Pricing*

━━━━━━━━━━━━━━━━━━━━━━━

📊 *STARTER SIGNALS PLAN*
• Daily signals on 3 major pairs
• Entry · SL · TP included
• Telegram delivery
💰 *$29 / month*

━━━━━━━━━━━━━━━━━━━━━━━

🚀 *PRO SIGNALS + EA PACK*
• All Starter features +
• Exclusive 2MA Andean EA file
• Setup & installation support
• Priority Telegram access
💰 *$79 / month*

━━━━━━━━━━━━━━━━━━━━━━━

👑 *MANAGED ACCOUNT (VIP)*
• We trade your account for you
• Profit share: 30% of gains
• Min deposit: $500
• Monthly performance report
💰 *30% profit share*

━━━━━━━━━━━━━━━━━━━━━━━

All plans paid via *USDT (TRC20)* — instant activation.
"""

HOW_IT_WORKS = """\
⚙️ *How ForexPro Works*

━━━━━━━━━━━━━━━━━━━━━━━

Our signals are generated by a battle-tested algorithm:

📈 *Strategy: 2MA + Andean Oscillator*
• Symbols: EURUSD · EURCAD · USDCAD
• Timeframe: 4H
• Backtested: Jan 2019 — Oct 2023

*Signal logic:*
1️⃣ Fast MA (50) crosses above Slow MA (200) → trend filter
2️⃣ Andean Oscillator Bull component crosses Signal → entry trigger
3️⃣ Dynamic Stop Loss based on recent swing levels
4️⃣ Trailing Stop at 50% level for maximum profit capture
5️⃣ Grid system adds to winning positions intelligently

This is not guesswork — it is systematic, data-driven trading.
"""

SIGNAL_EXAMPLE = """\
📡 *Live Signal — ForexPro*

━━━━━━━━━━━━━━━━━━━━━━━
🔷 Pair:       *EURUSD*
📈 Direction:  *BUY*
━━━━━━━━━━━━━━━━━━━━━━━
🎯 Entry:      *1.0842*
🛡 Stop Loss:  *1.0798*
🏁 Take Profit: *1.0920*
━━━━━━━━━━━━━━━━━━━━━━━
📊 Strategy:   2MA + Andean Oscillator
⏱ Timeframe:  4H
🔒 Risk:        1-2% per trade
━━━━━━━━━━━━━━━━━━━━━━━
_Signal valid for 4H candle. Always manage your risk._

🔔 Subscribe for real-time alerts → /services
"""

PAYMENT_MSG = """\
💳 *Payment — ForexPro*

━━━━━━━━━━━━━━━━━━━━━━━
Pay securely with *USDT (TRC20)*

🏦 Wallet Address:
`TTWYTUp1VEbTkQJcwnmujwsfKJ6Ud3Y3au`

_(Tap to copy)_

━━━━━━━━━━━━━━━━━━━━━━━
*After payment:*
1. Send screenshot to @profxlover
2. State which plan you purchased
3. Get activated within 30 minutes

━━━━━━━━━━━━━━━━━━━━━━━
⚠️ Only send *USDT on TRC20 network*.
Other networks will result in lost funds.
"""

FAQ = """\
❓ *Frequently Asked Questions*

━━━━━━━━━━━━━━━━━━━━━━━

*Q: How many signals per week?*
A: 5–15 signals across all 3 pairs.

*Q: What broker should I use?*
A: Any MT5 broker. We recommend brokers with low spreads on EUR pairs.

*Q: Is the EA automated?*
A: Yes. Once installed, it trades fully automatically 24/5.

*Q: What is the win rate?*
A: Backtested 2019–2023 across EURUSD, EURCAD, USDCAD on 4H.

*Q: Can I start with a small account?*
A: Yes. We recommend minimum $200 for signals, $500 for managed.

*Q: How do I get support?*
A: Tap 'Live Support' anytime — we respond within minutes.
"""

CONTACT_MSG = """\
📞 *Contact ForexPro*

━━━━━━━━━━━━━━━━━━━━━━━
👤 Telegram:  @profxlover
🌐 Channel:   t.me/profxlover
💬 Response time: Under 30 minutes
⏰ Available: 6 days a week (Mon–Sat)

━━━━━━━━━━━━━━━━━━━━━━━
Tap the button below to message us directly.
"""

# ─── KEYBOARDS ────────────────────────────────────────────────────────────────

def main_menu_keyboard():
    return ReplyKeyboardMarkup([
        [KeyboardButton("📊 Signals"), KeyboardButton("💼 Services")],
        [KeyboardButton("⚙️ How It Works"), KeyboardButton("💳 Pay Now")],
        [KeyboardButton("❓ FAQ"), KeyboardButton("📞 Contact")],
    ], resize_keyboard=True)

def services_inline():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("🟢 Starter — $29/mo", callback_data="plan_starter")],
        [InlineKeyboardButton("🚀 Pro + EA — $79/mo", callback_data="plan_pro")],
        [InlineKeyboardButton("👑 Managed Account (VIP)", callback_data="plan_managed")],
        [InlineKeyboardButton("💳 Pay with USDT", callback_data="pay")],
    ])

def back_inline():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("← Back to Menu", callback_data="menu")],
        [InlineKeyboardButton("📞 Talk to Human", url=f"https://t.me/profxlover")],
    ])

def contact_inline():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("💬 Message @profxlover", url="https://t.me/profxlover")],
        [InlineKeyboardButton("📢 Join Channel", url=CHANNEL_URL)],
    ])

def pay_inline():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("✅ I've Paid — Notify Owner", callback_data="paid_notify")],
        [InlineKeyboardButton("📞 Need Help?", url="https://t.me/profxlover")],
    ])

# ─── HANDLERS ─────────────────────────────────────────────────────────────────

async def start(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    await update.message.reply_photo(
        photo="https://i.imgur.com/4M34hi2.png",  # Replace with your logo URL
        caption=WELCOME,
        parse_mode="Markdown",
        reply_markup=main_menu_keyboard(),
    )
    # Notify owner of new user
    try:
        await ctx.bot.send_message(
            OWNER_ID,
            f"🔔 *New user joined ForexPro!*\n"
            f"👤 Name: {user.full_name}\n"
            f"🆔 ID: `{user.id}`\n"
            f"🌐 Username: @{user.username or 'N/A'}",
            parse_mode="Markdown"
        )
    except Exception:
        pass

async def handle_text(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    text = update.message.text

    if text == "📊 Signals":
        await update.message.reply_text(
            SIGNAL_EXAMPLE, parse_mode="Markdown",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("🔔 Subscribe to Signals", callback_data="plan_pro")],
                [InlineKeyboardButton("💳 Pay Now", callback_data="pay")],
            ])
        )
    elif text == "💼 Services":
        await update.message.reply_text(
            SERVICES, parse_mode="Markdown", reply_markup=services_inline()
        )
    elif text == "⚙️ How It Works":
        await update.message.reply_text(
            HOW_IT_WORKS, parse_mode="Markdown", reply_markup=back_inline()
        )
    elif text == "💳 Pay Now":
        await update.message.reply_text(
            PAYMENT_MSG, parse_mode="Markdown", reply_markup=pay_inline()
        )
    elif text == "❓ FAQ":
        await update.message.reply_text(
            FAQ, parse_mode="Markdown", reply_markup=back_inline()
        )
    elif text == "📞 Contact":
        await update.message.reply_text(
            CONTACT_MSG, parse_mode="Markdown", reply_markup=contact_inline()
        )
    else:
        # Smart auto-reply for unknown messages
        await update.message.reply_text(
            "Thank you for reaching out to *ForexPro*! 👋\n\n"
            "Our team will respond shortly. In the meantime, "
            "explore our services using the menu below.",
            parse_mode="Markdown",
            reply_markup=main_menu_keyboard()
        )
        # Forward unknown message to owner
        try:
            user = update.effective_user
            await ctx.bot.send_message(
                OWNER_ID,
                f"💬 *Message from client:*\n"
                f"👤 {user.full_name} (@{user.username or 'N/A'})\n"
                f"🆔 `{user.id}`\n\n"
                f"📝 *Message:* {text}\n\n"
                f"Reply to them: tg://user?id={user.id}",
                parse_mode="Markdown"
            )
        except Exception:
            pass

async def handle_callback(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    data = query.data

    if data == "menu":
        await query.message.reply_text(
            WELCOME, parse_mode="Markdown", reply_markup=main_menu_keyboard()
        )
    elif data == "pay":
        await query.message.reply_text(
            PAYMENT_MSG, parse_mode="Markdown", reply_markup=pay_inline()
        )
    elif data == "plan_starter":
        await query.message.reply_text(
            "🟢 *Starter Plan — $29/month*\n\n"
            "• Daily signals on EURUSD, EURCAD, USDCAD\n"
            "• Full Entry, SL, TP levels\n"
            "• Telegram delivery\n\n"
            "Pay via USDT TRC20 and send screenshot to @profxlover.",
            parse_mode="Markdown", reply_markup=pay_inline()
        )
    elif data == "plan_pro":
        await query.message.reply_text(
            "🚀 *Pro + EA Pack — $79/month*\n\n"
            "• All Starter features\n"
            "• Exclusive 2MA + Andean Oscillator EA\n"
            "• MT5 setup & installation support\n"
            "• Backtested 2019–2023 (EURUSD, EURCAD, USDCAD 4H)\n"
            "• Priority support via Telegram\n\n"
            "Pay via USDT TRC20 and send screenshot to @profxlover.",
            parse_mode="Markdown", reply_markup=pay_inline()
        )
    elif data == "plan_managed":
        await query.message.reply_text(
            "👑 *Managed Account — VIP*\n\n"
            "• We trade your MT5 account for you\n"
            "• 30% profit share — you keep 70%\n"
            "• Minimum deposit: $500\n"
            "• Monthly performance report\n"
            "• Zero monthly fee — we earn only when you earn\n\n"
            "Contact @profxlover to get started.",
            parse_mode="Markdown", reply_markup=contact_inline()
        )
    elif data == "paid_notify":
        user = query.from_user
        await ctx.bot.send_message(
            OWNER_ID,
            f"💰 *Payment Notification!*\n\n"
            f"👤 {user.full_name} (@{user.username or 'N/A'})\n"
            f"🆔 `{user.id}`\n\n"
            f"✅ Client says they have paid.\n"
            f"Reply: tg://user?id={user.id}",
            parse_mode="Markdown"
        )
        await query.message.reply_text(
            "✅ *Payment notification sent!*\n\n"
            "Our team will verify and activate your account within *30 minutes*.\n\n"
            "If urgent, message us directly: @profxlover",
            parse_mode="Markdown"
        )

# ─── OWNER COMMANDS ───────────────────────────────────────────────────────────

async def broadcast(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    """Owner only: /broadcast Your message here"""
    if update.effective_user.id != OWNER_ID:
        return
    if not ctx.args:
        await update.message.reply_text("Usage: /broadcast Your message")
        return
    msg = " ".join(ctx.args)
    await update.message.reply_text(f"📢 Broadcast sent:\n\n{msg}", parse_mode="Markdown")

async def send_signal(update: Update, ctx: ContextTypes.DEFAULT_TYPE):
    """Owner only: /signal — sends sample signal"""
    if update.effective_user.id != OWNER_ID:
        return
    await update.message.reply_text(SIGNAL_EXAMPLE, parse_mode="Markdown")

# ─── MAIN ─────────────────────────────────────────────────────────────────────

def main():
    app = ApplicationBuilder().token(BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("services", lambda u, c: u.message.reply_text(SERVICES, parse_mode="Markdown", reply_markup=services_inline())))
    app.add_handler(CommandHandler("pay", lambda u, c: u.message.reply_text(PAYMENT_MSG, parse_mode="Markdown", reply_markup=pay_inline())))
    app.add_handler(CommandHandler("signal", send_signal))
    app.add_handler(CommandHandler("broadcast", broadcast))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))

    print("ForexPro Bot is running...")
    app.run_polling()

if __name__ == "__main__":
    main()
